[theme]

# Primary accent color for interactive elements.
primaryColor = "#09090a"

# Background color for the main content area.
backgroundColor = "#FFFFFF"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#bde3f1"

# Color used for almost all text.
textColor = "#09090a"

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
# Default: "sans serif"
font = "sans serif"
